# Generated by Django 5.2.5 on 2025-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='completed_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='response_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Response rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
