# Generated by Django 5.2.5 on 2025-10-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_serviceprovider_availability_status_and_more'),
        ('chat', '0002_alter_conversation_participants'),
        ('bookings', '0002_initial'),
        ('notifications', '0001_initial'),
        ('payments', '0001_initial'),
        ('services', '0002_servicepackage'),
    ]

    operations = [
        # Update foreign key constraints to use CASCADE deletion
        migrations.RunSQL(
            # Forward SQL - Update all foreign key constraints to CASCADE
            """
            -- Update accounts_customerprofile
            ALTER TABLE accounts_customerprofile 
            DROP CONSTRAINT IF EXISTS accounts_customerprofile_user_id_fkey;
            ALTER TABLE accounts_customerprofile 
            ADD CONSTRAINT accounts_customerprofile_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update accounts_otpverification
            ALTER TABLE accounts_otpverification 
            DROP CONSTRAINT IF EXISTS accounts_otpverification_user_id_fkey;
            ALTER TABLE accounts_otpverification 
            ADD CONSTRAINT accounts_otpverification_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update accounts_serviceprovider
            ALTER TABLE accounts_serviceprovider 
            DROP CONSTRAINT IF EXISTS accounts_serviceprovider_user_id_fkey;
            ALTER TABLE accounts_serviceprovider 
            ADD CONSTRAINT accounts_serviceprovider_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update bookings_booking
            ALTER TABLE bookings_booking 
            DROP CONSTRAINT IF EXISTS bookings_booking_customer_id_fkey;
            ALTER TABLE bookings_booking 
            ADD CONSTRAINT bookings_booking_customer_id_fkey 
            FOREIGN KEY (customer_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update chat_message
            ALTER TABLE chat_message 
            DROP CONSTRAINT IF EXISTS chat_message_sender_id_fkey;
            ALTER TABLE chat_message 
            ADD CONSTRAINT chat_message_sender_id_fkey 
            FOREIGN KEY (sender_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update chat_conversation_participants
            ALTER TABLE chat_conversation_participants 
            DROP CONSTRAINT IF EXISTS chat_conversation_participants_user_id_fkey;
            ALTER TABLE chat_conversation_participants 
            ADD CONSTRAINT chat_conversation_participants_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update django_admin_log
            ALTER TABLE django_admin_log 
            DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey;
            ALTER TABLE django_admin_log 
            ADD CONSTRAINT django_admin_log_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update notifications_notification
            ALTER TABLE notifications_notification 
            DROP CONSTRAINT IF EXISTS notifications_notification_user_id_fkey;
            ALTER TABLE notifications_notification 
            ADD CONSTRAINT notifications_notification_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update payments_payment
            ALTER TABLE payments_payment 
            DROP CONSTRAINT IF EXISTS payments_payment_user_id_fkey;
            ALTER TABLE payments_payment 
            ADD CONSTRAINT payments_payment_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update payments_transaction
            ALTER TABLE payments_transaction 
            DROP CONSTRAINT IF EXISTS payments_transaction_user_id_fkey;
            ALTER TABLE payments_transaction 
            ADD CONSTRAINT payments_transaction_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update payments_wallet
            ALTER TABLE payments_wallet 
            DROP CONSTRAINT IF EXISTS payments_wallet_user_id_fkey;
            ALTER TABLE payments_wallet 
            ADD CONSTRAINT payments_wallet_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            
            -- Update services_review
            ALTER TABLE services_review 
            DROP CONSTRAINT IF EXISTS services_review_customer_id_fkey;
            ALTER TABLE services_review 
            ADD CONSTRAINT services_review_customer_id_fkey 
            FOREIGN KEY (customer_id) REFERENCES accounts_user(id) ON DELETE CASCADE;
            """,
            
            # Reverse SQL - Restore original constraints (if needed)
            """
            -- Note: This is a destructive migration. 
            -- In production, you might want to backup data before running this.
            -- The reverse operation would require knowing the original constraint names.
            """
        ),
    ]
