# Generated by Django 5.2.5 on 2025-08-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='bookingavailability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.serviceprovider'),
        ),
    ]
